name: Plugin Build
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install ZIP
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run build and archive
        run: |
          make build
          make archive
        shell: bash
      
      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          name: plugin-archive
          path: build/plugin.smplug

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: build/plugin.smplug
