name: Plugin Build
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub global activate hetu_script_dev_tools
      
      - name: Add Pub Bin to Path
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Run build and archive
        run: |
          make build
          make archive
        shell: bash
      
      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          name: plugin-archive
          path: plugin.smplug

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: plugin.smplug
